FROM golang
ARG repo=countdown-exporter
ARG cgo=0
RUN mkdir -p /go/src/github.com/tmegow/${repo}
WORKDIR /go/src/github.com/tmegow/${repo}/
COPY . /go/src/github.com/tmegow/${repo}
RUN go get \
&& ( \
    [ "${cgo}" = "0" ] && CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -installsuffix cgo --ldflags '-extldflags "-static"' -v -o "/binary" \
    || CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -a --ldflags -w -v -o "/binary" \
)

CMD ["cat", "/binary"]
